version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
    volumes:
      - ./server/bookings.json:/app/bookings.json:rw

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
