name: Deploy web to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build web
        run: npm run build:web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./web-build
          publish_branch: gh-pages
          # For public repos GITHUB_TOKEN works. For private repos set PERSONAL_TOKEN secret with a PAT that has repo scope.
          github_token: ${{ secrets.GITHUB_TOKEN }}
