name: Deploy web to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web
        run: |
          npx expo --version
          npm run build:web

      - name: Show web-build contents (debug)
        run: |
          echo "web-build contents:" && ls -la web-build || echo "web-build not found"

      - name: Upload web-build for debugging
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-build-debug
          path: web-build
          if-no-files-found: warn

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./web-build
          publish_branch: gh-pages
          # For public repos GITHUB_TOKEN works. For private repos set PERSONAL_TOKEN secret with a PAT that has repo scope.
          github_token: ${{ secrets.GITHUB_TOKEN }}
